- id: nsx-t-hiera-override
  version: 2.0.0
  type: puppet
  groups:
    - primary-controller
    - controller
    - compute
  required_for:
    - netconfig
  requires:
    - globals
  parameters:
    puppet_manifest: puppet/manifests/hiera-override.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 120

- id: nsx-t-compute-vmware-nova-config
  version: 2.0.0
  type: puppet
  groups:
    - compute-vmware
  required_for:
    - enable_nova_compute_service
  requires:
    - top-role-compute-vmware
    - top-role-compute
  parameters:
    puppet_manifest: puppet/manifests/compute-vmware-nova-config.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 180

- id: nsx-t-compute-nova-config
  version: 2.0.0
  type: puppet
  groups:
    - compute
  required_for:
    - enable_nova_compute_service
  requires:
    - top-role-compute
    - openstack-network-compute-nova
  parameters:
    puppet_manifest: puppet/manifests/compute-nova-config.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 180

- id: nsx-t-gem-install
  version: 2.0.0
  type: puppet
  groups:
    - primary-controller
    - controller
    - compute
  required_for:
    - nsx-t-reg-node-on-management-plane
    - nsx-t-reg-node-as-transport-node
  requires:
    - setup_repositories
  parameters:
    puppet_manifest: puppet/manifests/gem-install.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 300

- id: nsx-t-create-repo
  version: 2.0.0
  type: puppet
  groups:
    - primary-controller
    - controller
    - compute
  required_for:
    - netconfig
  requires:
    - nsx-t-gem-install
  parameters:
    puppet_manifest: puppet/manifests/create-repo.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600
    strategy:
      type: one_by_one

- id: nsx-t-install-packages
  version: 2.0.0
  type: puppet
  groups:
    - primary-controller
    - controller
    - compute
  required_for:
    - openstack-network-start
    - database
    - primary-database
  requires:
    - netconfig
    - nsx-t-create-repo
  parameters:
    puppet_manifest: puppet/manifests/install-nsx-packages.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 300

- id: nsx-t-install-plugin
  version: 2.0.0
  type: puppet
  groups:
    - primary-controller
    - controller
  required_for:
    - openstack-network-end
  requires:
    - openstack-network-server-config
  parameters:
    puppet_manifest: puppet/manifests/install-nsx-plugin.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 60

- id: nsx-t-configure-plugin
  version: 2.0.0
  type: puppet
  groups:
    - primary-controller
    - controller
  required_for:
    - openstack-network-end
  requires:
    - nsx-t-install-plugin
  parameters:
    puppet_manifest: puppet/manifests/configure-plugin.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 60

- id: nsx-t-neutron-server-stop
  version: 2.0.0
  type: puppet
  groups:
    - primary-controller
    - controller
  required_for:
    - openstack-network-end
  requires:
    - openstack-network-server-config
  parameters:
    puppet_manifest: puppet/manifests/neutron-server-stop.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 60

- id: nsx-t-primary-neutron-server-start
  version: 2.0.0
  type: puppet
  groups:
    - primary-controller
  required_for:
    - primary-openstack-network-agents-metadata
    - primary-openstack-network-agents-dhcp
  requires:
    - nsx-t-configure-plugin
  cross-depends:
    - name: nsx-t-neutron-server-stop
  parameters:
    puppet_manifest: puppet/manifests/neutron-server-start.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 300

- id: nsx-t-reg-node-on-management-plane
  version: 2.0.0
  type: puppet
  groups:
    - primary-controller
    - controller
    - compute
  required_for:
    - primary-openstack-network-agents-metadata
    - primary-openstack-network-agents-dhcp
    - openstack-network-end
  requires:
    - nsx-t-configure-plugin
  parameters:
    puppet_manifest: puppet/manifests/reg-node-on-management-plane.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 300

- id: nsx-t-reg-node-as-transport-node
  version: 2.0.0
  type: puppet
  groups:
    - primary-controller
    - controller
    - compute
  required_for:
    - primary-openstack-network-agents-metadata
    - primary-openstack-network-agents-dhcp
    - openstack-network-end
  requires:
    - nsx-t-reg-node-on-management-plane
  parameters:
    puppet_manifest: puppet/manifests/reg-node-as-transport-node.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 300

- id: nsx-t-neutron-server-start
  version: 2.0.0
  type: puppet
  groups:
    - controller
  requires:
    - nsx-t-neutron-server-stop
    - nsx-t-configure-plugin
  required_for:
    - openstack-network-agents-metadata
    - openstack-network-agents-dhcp
  cross-depends:
    - name: nsx-t-primary-neutron-server-start
  parameters:
    puppet_manifest: puppet/manifests/neutron-server-start.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 120
    strategy:
      type: one_by_one

- id: nsx-t-primary-configure-agents-dhcp
  version: 2.0.0
  type: puppet
  groups:
    - primary-controller
  required_for:
    - openstack-network-end
  requires:
    - primary-openstack-network-agents-dhcp
  cross-depends:
    - name: nsx-t-configure-agents-dhcp
  parameters:
    puppet_manifest: puppet/manifests/configure-agents-dhcp.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 180

- id: nsx-t-configure-agents-dhcp
  version: 2.0.0
  type: puppet
  groups:
    - controller
  required_for:
    - openstack-network-end
  requires:
    - openstack-network-agents-dhcp
  parameters:
    puppet_manifest: puppet/manifests/configure-agents-dhcp.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 120

- id: nsx-t-neutron-network-create
  version: 2.1.0
  type: puppet
  groups:
    - primary-controller
  required_for:
    - openstack-network-routers
  requires:
    - nsx-t-primary-neutron-server-start
    - nsx-t-configure-agents-dhcp
    - primary-openstack-network-agents-metadata
  condition:
    yaql_exp: "changed($.quantum)"
  parameters:
    puppet_manifest: puppet/manifests/neutron-network-create.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 300

# skipped tasks
- id: openstack-network-networks
  version: 2.0.0
  type: skipped
- id: primary-openstack-network-plugins-l2
  version: 2.0.0
  type: skipped
- id: openstack-network-plugins-l2
  version: 2.0.0
  type: skipped
- id: primary-openstack-network-agents-l3
  version: 2.0.0
  type: skipped
- id: openstack-network-agents-l3
  version: 2.0.0
  type: skipped
- id: openstack-network-agents-sriov
  version: 2.0.0
  type: skipped
- id: enable_nova_compute_service
  version: 2.0.0
  type: skipped
