- id: nsx-t-create-repo
  version: 2.0.0
  type: puppet
  groups:
    - primary-controller
    - controller
    - compute
  required_for:
    - pre_deployment_end
  requires:
    - pre_deployment_start
  parameters:
    puppet_manifest: puppet/manifests/create-repo.pp
    puppet_modules: puppet/modules
    timeout: 120

- id: nsx-t-install-plugin
  version: 2.0.0
  type: puppet
  groups:
    - primary-controller
    - controller
  required_for:
    - nsx-t-configure-plugin
  requires:
    - openstack-network-common-config
  parameters:
    puppet_manifest: puppet/manifests/install-nsx-plugin.pp
    puppet_modules: puppet/modules
    timeout: 60

- id: nsx-t-configure-plugin
  version: 2.0.0
  type: puppet
  groups:
    - primary-controller
    - controller
  required_for:
    - openstack-network-neutron-start
  requires:
    - openstack-network-server-nova
  parameters:
    puppet_manifest: puppet/manifests/configure-plugin.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 60
